kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: kube-system
  name: role-pod-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-binding-reads-pods
  namespace: kube-system
subjects:
- kind: User
  name: cloudadmin
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: role-pod-reader
  apiGroup: rbac.authorization.k8s.io

